version: '3.9'

services:
    santaclaus:
        build: 
            dockerfile: Dockerfile
            args:
                EXEC_TYPE: ${EXEC_TYPE}
        container_name: santaclaus
        environment:
            SANTACLAUS_ADDRESS: ${SANTACLAUS_ADDRESS}
            SANTACLAUS_MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin
        
        expose:
            # - 8080
            - ${SANTACLAUS_PORT}
        networks:
            - mongo
            # - santaclaus:maestro
        depends_on:
            - mongo
        restart: on-failure

    mongo:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}      
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}     
        expose:
            # - 27017
            - ${MONGO_PORT}
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        restart: always

#    documentation:
#        build:
#            context: .
#            dockerfile: Dockerfile.documentation
#        ports:
#            - 50051:80

networks:
    mongo: null
    # santaclaus:maestro:
        # external: true

volumes:
    mongo: null