version: '3.9'

services:
    santaclaus:
        profiles:
            - launch
        build:
            dockerfile: Dockerfile
            args:
                EXEC_TYPE: ${EXEC_TYPE}
        container_name: santaclaus
        env_file:
            - ${SANTACLAUS_ENV_FILE}
        expose:
            - ${SANTACLAUS_PORT}
        ports:
            - ${SANTACLAUS_PORT}:${SANTACLAUS_PORT}
        networks:
            - maestro:santaclaus
            - chouf:santaclaus
            - santaclaus:bugle
        restart: unless-stopped

networks:
    maestro:santaclaus:
        external: true
    chouf:santaclaus:
        external: true
    santaclaus:bugle:
        external: true
