version: '3.9'

services:
    santaclaus:
        build: 
            dockerfile: Dockerfile
            args:
                EXEC_TYPE: ${EXEC_TYPE}
        container_name: santaclaus
        environment:
            SANTACLAUS_ADDRESS: ${SANTACLAUS_ADDRESS}
            SANTACLAUS_MONGO_DB: ${SANTACLAUS_MONGO_DB}
            SANTACLAUS_MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${SANTACLAUS_MONGO_DB}?authSource=admin
        
        expose:
            - ${SANTACLAUS_PORT}
        networks:
            - mongo
            # - santaclaus:maestro
        depends_on:
            - mongo
        restart: on-failure

    mongo:
        image: mongo:6
        environment:
            MONGO_INITDB_DATABASE: ${SANTACLAUS_MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        expose:
            - ${MONGO_PORT}
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        restart: always

networks:
    mongo: null
    # santaclaus:maestro:
        # external: true

volumes:
    mongo: null